/**
 * Seeds all blog posts with full Portable Text body content.
 * Also deletes any orphan drafts to fix Studio issues.
 *
 * Usage:  SANITY_TOKEN=sk... node scripts/seed-blogs.mjs
 */

import { createClient } from "@sanity/client";

const projectId = "k0r3y2my";
const dataset = "production";
const token = process.env.SANITY_TOKEN;

if (!token) {
  console.error("❌  Set SANITY_TOKEN env var.");
  process.exit(1);
}

const client = createClient({ projectId, dataset, token, apiVersion: "2024-01-01", useCdn: false });

// Helper: create a Portable Text block
let keyCounter = 0;
function k() { return `k${keyCounter++}`; }

function heading(text, style = "h2") {
  return { _type: "block", _key: k(), style, markDefs: [], children: [{ _type: "span", _key: k(), text, marks: [] }] };
}

function para(text) {
  return { _type: "block", _key: k(), style: "normal", markDefs: [], children: [{ _type: "span", _key: k(), text, marks: [] }] };
}

function bold(text) {
  return { _type: "block", _key: k(), style: "normal", markDefs: [], children: [{ _type: "span", _key: k(), text, marks: ["strong"] }] };
}

function bullet(text) {
  return { _type: "block", _key: k(), style: "normal", listItem: "bullet", level: 1, markDefs: [], children: [{ _type: "span", _key: k(), text, marks: [] }] };
}

function quote(text) {
  return { _type: "block", _key: k(), style: "blockquote", markDefs: [], children: [{ _type: "span", _key: k(), text, marks: [] }] };
}

// ── All Blog Posts ──

const posts = [
  // ─── 1 ───
  {
    slug: "what-to-expect-in-your-first-therapy-session",
    title: "What to Expect in Your First Therapy Session",
    description: "Feeling nervous about starting therapy? Here's a clear, reassuring guide to what happens in your first session — from preparation to what your therapist will ask.",
    category: "Therapy Basics",
    publishedAt: "2025-01-15",
    readingTime: "5 min read",
    body: [
      heading("It's Completely Normal to Feel Nervous"),
      para("If you're about to attend your first therapy session, you might be feeling a mix of emotions — hope, anxiety, curiosity, maybe even a little dread. That's completely normal. Most people feel some level of nervousness before their first session, and that's okay."),
      heading("Before the Session"),
      para("Here are a few things you can do to prepare:"),
      bullet("Complete any intake forms your therapist sends — fill them out honestly"),
      bullet("Find a quiet, private space since sessions are online. Use headphones if it helps"),
      bullet("Test your internet connection, camera, and microphone a few minutes before"),
      bullet("Jot down what brought you to therapy and what you'd like to work on"),
      heading("What Actually Happens"),
      para("The first session — sometimes called an intake or assessment session — is mostly about getting to know each other:"),
      bullet("Introductions and rapport building — your therapist creates a warm, welcoming space"),
      bullet("Understanding your concerns — share what brought you here, at your own pace"),
      bullet("Background information — personal history, relationships, work, health"),
      bullet("Setting goals together — mapping out what you'd like to achieve"),
      bullet("Questions and logistics — session frequency, confidentiality, and process"),
      heading("What You Don't Need to Worry About"),
      para("There's no \"right\" way to do therapy. You don't need to have your thoughts perfectly organised. You don't need to cry (though it's perfectly fine if you do). You don't need to impress your therapist. This space is entirely for you."),
      heading("After the Session"),
      para("You might feel lighter, or you might feel emotionally stirred up. Both are normal responses. Give yourself time to decompress — take a walk, journal, or simply rest. Over the next few sessions, you'll settle into the process and begin noticing shifts."),
      quote("Therapy is not about being \"broken.\" It's about being brave enough to grow."),
      para("Ready to take the next step? Book your first session or start with a free 15-minute discovery call."),
    ],
  },
  // ─── 2 ───
  {
    slug: "understanding-anxiety-signs-and-coping-strategies",
    title: "Understanding Anxiety: Signs, Symptoms & Evidence-Based Coping Strategies",
    description: "Learn to recognise anxiety symptoms — physical, emotional, and behavioural — and discover 6 practical, evidence-based strategies to manage anxious thoughts.",
    category: "Mental Health",
    publishedAt: "2025-01-22",
    readingTime: "7 min read",
    body: [
      heading("What Is Anxiety, Really?"),
      para("Anxiety is your body's natural response to perceived threat or stress. In small doses, it's helpful — it keeps you alert and motivated. But when anxiety becomes persistent, overwhelming, or disproportionate, it starts to interfere with daily life."),
      heading("Physical Signs"),
      bullet("Racing or pounding heartbeat"),
      bullet("Shortness of breath or chest tightness"),
      bullet("Muscle tension, especially in the jaw, neck, or shoulders"),
      bullet("Stomach problems — nausea, churning, or loss of appetite"),
      bullet("Difficulty sleeping or restless sleep"),
      bullet("Fatigue and exhaustion, even after rest"),
      heading("Emotional & Cognitive Signs"),
      bullet("Constant worry or \"what if\" thinking"),
      bullet("Feeling on edge or restless"),
      bullet("Difficulty concentrating or mind going blank"),
      bullet("Irritability or emotional sensitivity"),
      bullet("A sense of impending doom or dread"),
      heading("Behavioural Signs"),
      bullet("Avoiding certain situations, places, or people"),
      bullet("Procrastinating due to fear of failure"),
      bullet("Seeking constant reassurance from others"),
      heading("6 Evidence-Based Coping Strategies"),
      heading("1. Grounding Techniques (5-4-3-2-1)", "h3"),
      para("Name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, and 1 you can taste. This brings you back to the present moment."),
      heading("2. Box Breathing", "h3"),
      para("Inhale for 4 counts, hold for 4, exhale for 4, hold for 4. Repeat 4–5 times. This activates your parasympathetic nervous system."),
      heading("3. Challenge Anxious Thoughts", "h3"),
      para("Ask yourself: \"Is this thought based on facts or feelings? What would I say to a friend thinking this?\" This is a core CBT technique."),
      heading("4. Limit Avoidance", "h3"),
      para("Avoidance feels good short-term but reinforces anxiety long-term. Gradually facing feared situations helps your brain learn the threat is manageable."),
      heading("5. Build Routine and Structure", "h3"),
      para("Anxiety thrives on uncertainty. A predictable daily routine — regular sleep, meals, movement — significantly reduces baseline anxiety."),
      heading("6. Physical Movement", "h3"),
      para("Even a 20-minute walk lowers cortisol and boosts mood-regulating neurotransmitters. It's one of the most powerful anxiety reducers available."),
      heading("When to Seek Professional Help"),
      para("If anxiety is interfering with your work, relationships, sleep, or quality of life — it's time to talk to a professional. CBT, DBT, and mindfulness-based interventions are highly effective."),
    ],
  },
  // ─── 3 ───
  {
    slug: "how-to-communicate-better-in-your-relationship",
    title: "How to Communicate Better in Your Relationship: 5 Proven Techniques",
    description: "Communication is the foundation of healthy relationships. Learn 5 powerful, therapist-approved techniques to improve how you and your partner connect.",
    category: "Relationships",
    publishedAt: "2025-02-01",
    readingTime: "6 min read",
    body: [
      heading("Why Communication Breaks Down"),
      para("Most relationship conflicts aren't really about the dishes or who forgot to reply. They're about unmet needs, unspoken expectations, and feeling unheard. The good news? Communication is a skill that can be learned."),
      heading("1. Use \"I\" Statements"),
      para("Instead of \"You never listen to me,\" try \"I feel unheard when I'm speaking and I notice you're on your phone.\" This expresses your experience without blame."),
      heading("2. Listen to Understand, Not to Respond"),
      para("Active listening means giving your full attention, reflecting back what you heard, and asking clarifying questions. Try: \"What I'm hearing is…\" then ask \"Did I get that right?\""),
      heading("3. Take Healthy Time-Outs"),
      para("When emotions escalate, it's okay to press pause. Say: \"I need 20 minutes to calm down. I'll come back and we can continue.\" Then follow through."),
      heading("4. Express Appreciation Regularly"),
      para("Relationships that thrive have at least 5 positive interactions for every 1 negative one. Make daily gratitude and acknowledgment a habit — not just during conflict."),
      heading("5. Repair After Conflict"),
      para("No couple communicates perfectly. A sincere apology, gentle humour, or simply \"I didn't handle that well — can we try again?\" goes a long way."),
      heading("When Communication Problems Persist"),
      para("If you keep having the same arguments or feel emotionally distant, couples therapy can help. A therapist provides a safe, structured space to learn new tools and rebuild connection."),
    ],
  },
  // ─── 4 ───
  {
    slug: "breaking-the-stigma-mental-health-in-indian-culture",
    title: "Breaking the Stigma: Mental Health in Indian Culture — Why It's Okay to Ask for Help",
    description: "Exploring cultural barriers to mental health support in India — family pressure, stigma, and why seeking therapy is an act of strength, not weakness.",
    category: "Cultural Perspectives",
    publishedAt: "2025-02-10",
    readingTime: "8 min read",
    body: [
      heading("The Elephant in the Room"),
      para("In many Indian households, mental health is still the elephant in the room. Phrases like \"log kya kahenge?\" and \"therapy sirf pagal logon ke liye hai\" create real barriers that prevent millions from accessing support."),
      heading("Why the Stigma Exists"),
      bullet("Collectivist values — family reputation often takes priority over individual well-being"),
      bullet("Lack of mental health literacy — emotional distress dismissed as weakness"),
      bullet("Religious frameworks sometimes replace professional help"),
      bullet("Gender expectations — men expected to be stoic, women's struggles dismissed"),
      bullet("Limited access — fewer than 1 psychiatrist per 100,000 people in India"),
      heading("The Cost of Silence"),
      para("When we don't talk about mental health, people suffer alone. India has one of the highest rates of suicide in the world, particularly among young people aged 15–29. Behind every statistic is a person who didn't get the help they needed."),
      heading("How Things Are Changing"),
      bullet("Public figures speaking openly about their mental health journeys"),
      bullet("Instagram and YouTube making mental health education accessible in regional languages"),
      bullet("Online therapy removing geographical barriers entirely"),
      bullet("Younger generations willing to question outdated norms"),
      heading("What You Can Do"),
      bullet("Start the conversation — talk about feelings openly with friends and family"),
      bullet("Educate yourself — learn to recognise signs of common mental health conditions"),
      bullet("Challenge stigma gently — offer a different perspective when someone dismisses mental health"),
      bullet("Lead by example — share your experience if you've benefited from therapy"),
      quote("Seeking help is not a sign of weakness. It's a sign of self-awareness, courage, and the desire to live a better life."),
    ],
  },
  // ─── 5 ───
  {
    slug: "self-care-is-not-selfish-building-a-sustainable-routine",
    title: "Self-Care Is Not Selfish: How to Build a Sustainable Self-Care Routine That Actually Works",
    description: "Move beyond bubble baths. Learn what genuine self-care looks like across 4 pillars — physical, emotional, social, and mental — with practical tips to build lasting habits.",
    category: "Self-Care",
    publishedAt: "2025-02-20",
    readingTime: "5 min read",
    body: [
      heading("What Self-Care Actually Means"),
      para("Self-care has become a buzzword, often reduced to spa days and scented candles. Genuine self-care goes deeper — it's about consistently meeting your own needs so you can function at your best. Sometimes it looks like going to bed on time or having a difficult conversation."),
      heading("Why We Struggle with Self-Care"),
      para("Many of us — especially women, caregivers, and people from collectivist cultures — are taught to put others first. But you cannot pour from an empty cup. Neglecting your needs doesn't make you a better person; it makes you depleted."),
      heading("Physical Self-Care"),
      bullet("Regular sleep (7–9 hours, consistent schedule)"),
      bullet("Nourishing food that makes you feel good"),
      bullet("Movement you enjoy — walking, dancing, yoga"),
      bullet("Regular medical check-ups"),
      heading("Emotional Self-Care"),
      bullet("Allowing yourself to feel without judgement"),
      bullet("Journaling or creative expression"),
      bullet("Setting boundaries with draining people"),
      bullet("Therapy or counselling when needed"),
      heading("Social Self-Care"),
      bullet("Spending time with people who uplift you"),
      bullet("Asking for help when you need it"),
      bullet("Saying no without guilt"),
      heading("Mental Self-Care"),
      bullet("Taking breaks from screens and social media"),
      bullet("Learning something new for the joy of it"),
      bullet("Practising mindfulness or meditation"),
      heading("Building a Routine That Sticks"),
      bullet("Start small — even 10 minutes of intentional self-care daily"),
      bullet("Anchor to existing habits — breathe deeply while your chai brews"),
      bullet("Schedule it — treat self-care like a work meeting"),
      bullet("Be flexible — your routine should evolve with you"),
      quote("Self-care is not selfish. It's the foundation that allows you to show up for everyone and everything that matters to you."),
    ],
  },
  // ─── 6 ───
  {
    slug: "when-should-you-consider-couples-therapy",
    title: "When Should You Consider Couples Therapy? 6 Signs It's Time",
    description: "Couples therapy isn't just for crises. Here are 6 clear signs that you and your partner could benefit from professional support — and what to expect.",
    category: "Relationships",
    publishedAt: "2025-03-01",
    readingTime: "6 min read",
    body: [
      heading("It's Not Just for \"Bad\" Relationships"),
      para("There's a misconception that couples therapy is a last resort. The most successful outcomes happen when couples seek support before things reach a breaking point — like physiotherapy for a sore joint before it becomes debilitating."),
      heading("1. Communication Has Broken Down"),
      para("You avoid difficult conversations, or every talk turns into an argument. You feel like you're speaking different languages."),
      heading("2. The Same Arguments Keep Repeating"),
      para("You fight about the same issues without resolution. This often signals deeper unmet needs that haven't been addressed."),
      heading("3. Emotional or Physical Distance"),
      para("You feel more like roommates than partners. Intimacy — emotional or physical — has faded."),
      heading("4. Trust Has Been Damaged"),
      para("Whether through infidelity, dishonesty, or broken promises, trust is difficult to rebuild without professional guidance."),
      heading("5. A Major Life Transition"),
      para("Moving cities, having a baby, career changes, loss — major transitions put stress on relationships. Therapy helps you adapt together."),
      heading("6. You're Considering Separation"),
      para("Therapy can help you either find a path forward together or part ways with clarity and mutual respect. Both are valid outcomes."),
      heading("What Happens in Couples Therapy?"),
      bullet("Identifying unhelpful communication patterns"),
      bullet("Learning to express needs without blame"),
      bullet("Developing active listening and empathy skills"),
      bullet("Exploring attachment styles"),
      bullet("Building practical conflict resolution strategies"),
      para("Your therapist won't take sides — their role is to create a safe space where both partners can be heard."),
    ],
  },
  // ─── 7 ───
  {
    slug: "managing-academic-pressure-a-guide-for-teenagers",
    title: "Managing Academic Pressure: A Complete Guide for Teenagers & Parents in India",
    description: "Academic stress is real and rising. Practical, evidence-based tips for Indian teens and their parents to manage expectations, build resilience, and protect mental health.",
    category: "Mental Health",
    publishedAt: "2025-03-10",
    readingTime: "6 min read",
    body: [
      heading("The Weight of Expectations"),
      para("For many teenagers in India, academic performance is tied to self-worth, family pride, and future security. The pressure to crack competitive exams and maintain high percentages can feel relentless and lead to anxiety, burnout, and depression."),
      heading("Warning Signs"),
      bullet("Constant worry about results, even after putting in effort"),
      bullet("Difficulty sleeping or nightmares about exams"),
      bullet("Loss of interest in hobbies, friends, or activities"),
      bullet("Irritability, mood swings, or emotional outbursts"),
      bullet("Physical symptoms — headaches, stomach aches, fatigue"),
      bullet("Perfectionism — feeling anything less than the best is failure"),
      bullet("Statements like \"I'm not good enough\" or \"What's the point?\""),
      heading("For Teenagers: Practical Strategies"),
      heading("Break Tasks into Smaller Steps", "h3"),
      para("Focus on one chapter, one concept, one practice set at a time. Progress is progress, no matter how small."),
      heading("Use the Pomodoro Technique", "h3"),
      para("25 minutes of focused study, 5-minute break. After 4 rounds, take a longer break. Your brain needs rest to retain information."),
      heading("Maintain a Life Outside Studies", "h3"),
      para("Hobbies, physical activity, friendships, and creative outlets aren't distractions — they're essential for a balanced mind."),
      heading("For Parents: How You Can Help"),
      bullet("Check your own expectations — are they based on your child's abilities or comparison?"),
      bullet("Praise effort, not just results"),
      bullet("Create space for honest conversations — and really listen"),
      bullet("Model healthy coping — your child learns from watching you"),
      bullet("Know when to seek help — persistent distress needs professional attention"),
      quote("Your worth is not defined by a number on a marksheet. You are so much more than your grades."),
    ],
  },
  // ─── 8 ───
  {
    slug: "therapy-for-nris-why-cultural-context-matters",
    title: "Therapy for NRIs: Why Cultural Context Matters More Than You Think",
    description: "Living abroad as an Indian comes with unique psychological challenges. Here's why a culturally sensitive therapist can make all the difference for NRIs.",
    category: "Cultural Perspectives",
    publishedAt: "2025-03-20",
    readingTime: "7 min read",
    body: [
      heading("The Unique Challenges of Being an NRI"),
      bullet("Identity conflicts — feeling \"too Indian\" in one context and \"not Indian enough\" in another"),
      bullet("Homesickness and loneliness — missing family, festivals, and belonging"),
      bullet("Family pressure from afar — expectations about marriage, career, money"),
      bullet("Relationship strain — intercultural dynamics and long-distance family"),
      bullet("Discrimination and microaggressions"),
      bullet("Career and visa stress — constant immigration anxiety"),
      heading("Why a Regular Therapist Might Not Get It"),
      para("A therapist unfamiliar with Indian culture might underestimate the role of family, misinterpret collectivist values as codependency, or push Western models of individuality that don't fully resonate."),
      heading("What Culturally Sensitive Therapy Looks Like"),
      bullet("Understanding Indian family dynamics without pathologising them"),
      bullet("Acknowledging the real impact of racism and cultural displacement"),
      bullet("Respecting spiritual beliefs as part of your coping toolkit"),
      bullet("Adapting therapeutic approaches to fit your worldview"),
      bullet("Speaking your language — literally and figuratively"),
      heading("The Advantage of Online Therapy"),
      para("You can connect with an Indian therapist who understands your background, regardless of where in the world you live. Sessions can be in English, Hindi, Bengali, or a comfortable mix."),
      para("Living abroad doesn't mean you have to navigate your mental health alone."),
    ],
  },
  // ─── 9 ───
  {
    slug: "the-difference-between-sadness-and-depression",
    title: "Sadness vs Depression: How to Tell the Difference & When to Seek Help",
    description: "Everyone feels sad sometimes. But when does sadness become clinical depression? Learn the key differences, warning signs, and what to do if you think you're depressed.",
    category: "Mental Health",
    publishedAt: "2025-04-01",
    readingTime: "5 min read",
    body: [
      heading("Sadness Is Normal. Depression Is Different."),
      para("Sadness comes in response to loss, disappointment, or difficult events. It passes. Depression is persistent — affecting how you think, feel, and function for weeks, months, or years."),
      heading("Sadness"),
      bullet("Has a clear trigger"),
      bullet("Comes and goes — you can still enjoy some things"),
      bullet("Doesn't usually affect ability to work, eat, or sleep for long"),
      bullet("Gradually lifts with support and time"),
      heading("Depression"),
      bullet("May or may not have a clear trigger"),
      bullet("Persistent low mood for most of the day, nearly every day, for 2+ weeks"),
      bullet("Loss of interest or pleasure in things you used to enjoy"),
      bullet("Significant changes in appetite, sleep, or energy"),
      bullet("Difficulty concentrating or making decisions"),
      bullet("Feelings of worthlessness or excessive guilt"),
      bullet("In severe cases, thoughts of death or suicide"),
      heading("The Grey Area"),
      para("Some people with depression still go to work and appear \"fine.\" This is sometimes called high-functioning depression or persistent depressive disorder — and it's just as valid."),
      heading("What Causes Depression?"),
      bullet("Biology — changes in brain chemistry, hormones, genetics"),
      bullet("Psychology — thought patterns, coping styles, unresolved trauma"),
      bullet("Environment — chronic stress, isolation, financial hardship"),
      bullet("Culture — stigma, lack of support systems, gender expectations"),
      heading("What to Do If You Think You're Depressed"),
      bullet("Acknowledge it — naming what you're experiencing is the first step"),
      bullet("Talk to someone you trust"),
      bullet("Seek professional help — CBT and psychodynamic therapy have strong evidence"),
      bullet("Be patient with yourself — recovery isn't linear"),
      quote("You don't have to feel like this forever. With the right support, things can and do get better."),
    ],
  },
  // ─── 10 ───
  {
    slug: "how-to-support-a-loved-one-going-through-therapy",
    title: "How to Support a Loved One Going Through Therapy: A Practical Guide",
    description: "When someone you care about is in therapy, your support matters. Learn how to help without overstepping — what to say, what to avoid, and how to be present.",
    category: "Therapy Basics",
    publishedAt: "2025-04-10",
    readingTime: "5 min read",
    body: [
      heading("Your Support Matters More Than You Think"),
      para("When someone you love starts therapy, it can bring up a mix of feelings — relief, confusion, maybe even insecurity. Their decision to seek help is brave, and how you respond can make a real difference."),
      heading("What Helps"),
      bullet("Normalise it — \"I'm glad you're doing this for yourself\" goes a long way"),
      bullet("Don't pry — let them share on their own terms, in their own time"),
      bullet("Be patient — change takes time and the process isn't always linear"),
      bullet("Acknowledge their courage — starting therapy is harder than it looks"),
      bullet("Educate yourself — learn about their condition or read about therapy in general"),
      heading("What to Avoid"),
      bullet("\"What do you even talk about?\" — respect the confidentiality of their sessions"),
      bullet("\"You don't need therapy, just talk to me\" — therapy provides something different from friendship"),
      bullet("\"Are you fixed yet?\" — recovery isn't a switch, it's a journey"),
      bullet("Making it about you — their therapy is their space"),
      heading("How to Be Present"),
      para("Sometimes the most powerful thing you can do is simply be there. You don't need to have answers or solutions. Being a calm, non-judgmental presence — someone who listens without trying to fix — is a gift."),
      heading("When You Might Benefit Too"),
      para("Supporting someone through a mental health journey can be emotionally taxing. It's okay to seek your own support — whether through therapy, a support group, or simply talking to a trusted friend."),
      quote("You can't pour from an empty cup. Taking care of yourself is part of taking care of them."),
    ],
  },
  // ─── 11 (NEW) ───
  {
    slug: "what-is-cbt-and-how-does-it-work",
    title: "What Is CBT? A Simple Guide to Cognitive Behavioural Therapy",
    description: "Cognitive Behavioural Therapy (CBT) is one of the most effective treatments for anxiety, depression, and stress. Learn how it works, what to expect, and who it helps.",
    category: "Therapy Basics",
    publishedAt: "2025-04-20",
    readingTime: "6 min read",
    body: [
      heading("What Is CBT?"),
      para("Cognitive Behavioural Therapy (CBT) is a structured, evidence-based form of psychotherapy that focuses on the connection between your thoughts, feelings, and behaviours. It's one of the most widely researched and effective treatments available today."),
      heading("The Core Idea"),
      para("CBT is built on a simple but powerful principle: it's not the situation itself that causes distress — it's how you interpret the situation. By identifying and challenging unhelpful thought patterns, you can change how you feel and behave."),
      heading("How Does a CBT Session Work?"),
      bullet("Collaborative — you and your therapist work as a team"),
      bullet("Goal-oriented — each session has a clear focus"),
      bullet("Skill-building — you learn tools you can use between sessions"),
      bullet("Time-limited — typically 8–20 sessions depending on the concern"),
      bullet("Homework — yes, there's practice between sessions, and it matters"),
      heading("What CBT Helps With"),
      bullet("Anxiety disorders (generalised anxiety, social anxiety, panic)"),
      bullet("Depression and persistent low mood"),
      bullet("OCD (Obsessive-Compulsive Disorder)"),
      bullet("PTSD and trauma-related difficulties"),
      bullet("Insomnia and sleep problems"),
      bullet("Anger management"),
      bullet("Low self-esteem and negative self-talk"),
      heading("Common CBT Techniques"),
      heading("Thought Records", "h3"),
      para("Writing down automatic negative thoughts, examining the evidence for and against them, and developing more balanced alternatives."),
      heading("Behavioural Experiments", "h3"),
      para("Testing your predictions in real life. If you believe \"everyone will judge me,\" you might run a small experiment and observe what actually happens."),
      heading("Exposure", "h3"),
      para("Gradually and safely facing feared situations to reduce avoidance and anxiety over time."),
      heading("Is CBT Right for You?"),
      para("CBT works well for people who prefer a structured, practical approach. It's not about lying on a couch and talking about your childhood — it's about developing real-world skills to manage your mind. If you're curious whether CBT could help, a therapist can assess your needs in the first session."),
    ],
  },
  // ─── 12 (NEW) ───
  {
    slug: "how-online-therapy-works-and-why-its-effective",
    title: "How Online Therapy Works in India: Benefits, Process & What to Expect",
    description: "Wondering if online therapy really works? Learn how virtual sessions are conducted, why research supports them, and how to get the most out of online counselling in India.",
    category: "Therapy Basics",
    publishedAt: "2025-05-01",
    readingTime: "6 min read",
    body: [
      heading("Is Online Therapy as Good as In-Person?"),
      para("Short answer: yes. Multiple research studies have shown that online therapy (also called teletherapy or virtual counselling) is just as effective as face-to-face sessions for most conditions, including anxiety, depression, and relationship concerns."),
      heading("How Does It Work?"),
      bullet("Sessions are conducted via secure video call (Google Meet, Zoom, or a similar platform)"),
      bullet("You sit in a private, comfortable space — your room, your office, wherever feels safe"),
      bullet("Sessions are typically 45–50 minutes, just like in-person therapy"),
      bullet("You can attend from anywhere in India — or abroad"),
      bullet("All you need is a stable internet connection and a device with a camera"),
      heading("Benefits of Online Therapy"),
      heading("Accessibility", "h3"),
      para("No commute, no waiting rooms. Especially valuable if you live in a city with heavy traffic, a smaller town without therapists, or outside India entirely."),
      heading("Comfort", "h3"),
      para("Being in your own space can make it easier to open up. Many people find they're more honest and relaxed at home."),
      heading("Flexibility", "h3"),
      para("Evening and weekend slots are easier to offer online. You can fit therapy around your schedule, not the other way around."),
      heading("Privacy", "h3"),
      para("No risk of running into someone at a clinic. Particularly important in Indian communities where stigma is still prevalent."),
      heading("Getting the Most Out of It"),
      bullet("Treat it like an in-person appointment — show up on time, dressed and present"),
      bullet("Find a private space where you won't be interrupted"),
      bullet("Put your phone on silent and close other tabs"),
      bullet("Be honest — your therapist can only help with what you share"),
      bullet("Do the work between sessions — therapy is a weekly practice, not a weekly event"),
      heading("Is Online Therapy Right for You?"),
      para("Online therapy is suitable for most concerns. However, if you're in a crisis, experiencing severe psychosis, or need in-person assessment, your therapist may recommend additional in-person support."),
    ],
  },
  // ─── 13 (NEW) ───
  {
    slug: "how-to-deal-with-burnout-signs-recovery-and-prevention",
    title: "How to Deal with Burnout: Signs, Recovery & Prevention Strategies",
    description: "Burnout is more than being tired. Learn to recognise the signs of burnout, understand why it happens, and discover practical strategies for recovery and prevention.",
    category: "Mental Health",
    publishedAt: "2025-05-10",
    readingTime: "7 min read",
    body: [
      heading("Burnout Is Not Just Being Tired"),
      para("Burnout is a state of chronic physical, emotional, and mental exhaustion caused by prolonged stress — usually from work, caregiving, or academic pressure. It's not something you can fix with a weekend off. It's a systemic problem that requires intentional change."),
      heading("The Three Dimensions of Burnout"),
      heading("1. Exhaustion", "h3"),
      para("Feeling drained all the time, even after sleep. Physical symptoms like headaches, muscle pain, and frequent illness are common."),
      heading("2. Cynicism / Detachment", "h3"),
      para("Feeling disconnected from your work, relationships, or purpose. You stop caring about things that used to matter. Everything feels pointless."),
      heading("3. Reduced Effectiveness", "h3"),
      para("Declining performance despite working harder. Tasks that used to be easy feel impossible. You doubt your own competence."),
      heading("Warning Signs"),
      bullet("Dreading Monday morning — or every morning"),
      bullet("Inability to \"switch off\" even during rest"),
      bullet("Emotional numbness or feeling flat"),
      bullet("Increased irritability with family and colleagues"),
      bullet("Physical symptoms — insomnia, digestive issues, frequent colds"),
      bullet("Relying on caffeine, alcohol, or screens to cope"),
      bullet("Withdrawing from social connections"),
      heading("Why It Happens"),
      bullet("Unsustainable workload without adequate recovery"),
      bullet("Lack of autonomy or control over your schedule"),
      bullet("Absence of recognition or meaning in work"),
      bullet("Poor boundaries between work and personal life"),
      bullet("Cultural pressure to always be productive (hustle culture)"),
      heading("Recovery Strategies"),
      bullet("Acknowledge it — burnout is real, not a personal failure"),
      bullet("Audit your commitments — identify what can be dropped or delegated"),
      bullet("Rebuild boundaries — set a hard stop time, protect weekends"),
      bullet("Prioritise sleep — it's not optional, it's foundational"),
      bullet("Move your body — gentle exercise, not intense workouts"),
      bullet("Reconnect with joy — what did you enjoy before the burnout?"),
      bullet("Seek professional help — therapy can help you understand the patterns that led here"),
      quote("You are not a machine. Rest is not earned — it's required."),
    ],
  },
  // ─── 14 (NEW) ───
  {
    slug: "understanding-attachment-styles-and-how-they-affect-relationships",
    title: "Understanding Attachment Styles: How They Shape Your Relationships",
    description: "Your attachment style — formed in childhood — affects how you love, fight, and connect. Learn about the 4 attachment styles and how therapy can help you build healthier bonds.",
    category: "Relationships",
    publishedAt: "2025-05-20",
    readingTime: "7 min read",
    body: [
      heading("What Are Attachment Styles?"),
      para("Attachment theory, developed by John Bowlby and Mary Ainsworth, explains how early relationships with caregivers shape our patterns of connection in adult relationships. Your attachment style influences how you handle intimacy, conflict, and emotional closeness."),
      heading("The 4 Attachment Styles"),
      heading("1. Secure Attachment", "h3"),
      para("You feel comfortable with intimacy and independence. You communicate needs clearly, handle conflict constructively, and trust your partner. About 50–60% of people fall into this category."),
      heading("2. Anxious (Preoccupied) Attachment", "h3"),
      para("You crave closeness but fear abandonment. You might overanalyse texts, need constant reassurance, or feel like you care more than your partner. You're highly attuned to shifts in your partner's mood."),
      heading("3. Avoidant (Dismissive) Attachment", "h3"),
      para("You value independence and self-sufficiency, sometimes at the cost of emotional closeness. You might pull away when things get intense, struggle to express feelings, or feel \"suffocated\" by needy partners."),
      heading("4. Disorganised (Fearful-Avoidant) Attachment", "h3"),
      para("You want closeness but are also afraid of it. Relationships feel confusing — you might oscillate between clinging and pushing away. This often stems from childhood environments that were both a source of comfort and fear."),
      heading("How Attachment Styles Play Out"),
      bullet("Anxious + Avoidant = the most common pairing, and the most volatile. One pursues, the other withdraws."),
      bullet("Anxious + Anxious = intense connection but also intense insecurity"),
      bullet("Secure + anyone = tends to stabilise the relationship"),
      heading("Can You Change Your Attachment Style?"),
      para("Yes. Attachment styles aren't fixed. With self-awareness, healthy relationships, and especially therapy, you can develop what's called \"earned secure attachment.\" The process involves understanding your patterns, processing childhood experiences, and practising new relational skills."),
      heading("How Therapy Helps"),
      bullet("Identifying your attachment style and its origins"),
      bullet("Understanding your triggers in relationships"),
      bullet("Learning to regulate emotions during conflict"),
      bullet("Developing secure communication patterns"),
      bullet("Healing wounds from early relationships"),
      para("Understanding your attachment style isn't about labelling yourself — it's about gaining insight into why you relate the way you do, and choosing to grow from there."),
    ],
  },
  // ─── 15 (NEW) ───
  {
    slug: "mental-health-tips-for-working-professionals-in-india",
    title: "Mental Health Tips for Working Professionals in India: Surviving the Hustle",
    description: "Indian work culture can be brutal on mental health. Practical, realistic tips for working professionals to protect their well-being without quitting their jobs.",
    category: "Self-Care",
    publishedAt: "2025-06-01",
    readingTime: "6 min read",
    body: [
      heading("The Indian Work Culture Problem"),
      para("Long hours, constant availability on WhatsApp groups, boss pressure, family expectations, and the glorification of \"hustle culture\" — Indian professionals face a unique cocktail of stressors that takes a serious toll on mental health."),
      heading("Signs Your Work Is Affecting Your Mental Health"),
      bullet("Sunday evening dread that starts Saturday afternoon"),
      bullet("Checking work messages first thing in the morning and last thing at night"),
      bullet("Irritability with family after work — snapping at people you love"),
      bullet("Physical symptoms — headaches, back pain, digestive issues"),
      bullet("Loss of interest in hobbies or social life"),
      bullet("Feeling like your identity is entirely tied to your job"),
      heading("Practical Tips That Actually Work"),
      heading("1. Set a Hard Stop", "h3"),
      para("Pick a time — 7pm, 8pm, whatever works — and stop working. Close the laptop. Mute work groups. Your brain needs a daily recovery window."),
      heading("2. Protect Your Mornings", "h3"),
      para("Don't open email first thing. Give yourself 30 minutes for something nourishing — chai, a walk, journaling, stretching. How you start your day sets the tone."),
      heading("3. Use Your Leave", "h3"),
      para("Indian professionals are notorious for hoarding leave. Your leave exists for a reason. Take mental health days. You don't need to be physically ill to take time off."),
      heading("4. Build Micro-Breaks Into Your Day", "h3"),
      para("5 minutes of deep breathing between meetings. A short walk after lunch. Stretching at your desk. Small breaks compound into significant stress reduction."),
      heading("5. Talk About It", "h3"),
      para("Find one trusted colleague, friend, or therapist you can be honest with. Isolation amplifies stress; connection reduces it."),
      heading("6. Redefine Success", "h3"),
      para("Success isn't just promotions and salary hikes. It's also sleeping well, having energy for your family, maintaining your health, and feeling at peace. Redefine what \"making it\" means to you."),
      heading("When to Seek Professional Help"),
      para("If work stress is affecting your sleep, relationships, appetite, or mood for more than a couple of weeks, it's time to talk to a professional. Therapy isn't just for crises — it's also for building resilience before things get worse."),
      quote("Your job is what you do. It's not who you are. Protect the person behind the professional."),
    ],
  },
  // ─── 16 (NEW) ───
  {
    slug: "how-to-set-healthy-boundaries-without-feeling-guilty",
    title: "How to Set Healthy Boundaries Without Feeling Guilty — A Therapist's Guide",
    description: "Boundaries aren't selfish — they're essential. Learn why boundaries matter, how to set them with family, friends, and work, and how to handle guilt when you do.",
    category: "Self-Care",
    publishedAt: "2025-06-10",
    readingTime: "6 min read",
    body: [
      heading("What Are Boundaries, Really?"),
      para("Boundaries are the limits you set to protect your energy, time, and emotional well-being. They're not walls — they're guidelines for how you want to be treated and what you're willing to accept."),
      heading("Why Boundaries Feel Hard (Especially in Indian Culture)"),
      para("In collectivist cultures, boundaries can feel like betrayal. Saying \"no\" to a parent, setting limits with in-laws, or telling a friend you need space can trigger immense guilt. But boundaries aren't about rejecting people — they're about respecting yourself."),
      heading("Types of Boundaries"),
      bullet("Emotional — limiting how much of others' emotions you absorb"),
      bullet("Time — protecting your schedule and energy"),
      bullet("Physical — your space, your body, your comfort"),
      bullet("Digital — screen time, social media, work messages after hours"),
      bullet("Financial — how you spend, lend, and share money"),
      heading("How to Set Boundaries — Practical Scripts"),
      heading("With Family", "h3"),
      para("\"I love you and I need some time to myself this weekend. I'll call you on Monday.\""),
      heading("With Friends", "h3"),
      para("\"I can't make it tonight, but I'd love to catch up next week when I have more energy.\""),
      heading("At Work", "h3"),
      para("\"I can take this on, but I'll need to push back the other deadline. Which is the priority?\""),
      heading("With a Partner", "h3"),
      para("\"When you raise your voice, I shut down. Can we agree to take a break when things get heated?\""),
      heading("Dealing with Guilt"),
      bullet("Remind yourself: guilt is a feeling, not a fact. Feeling guilty doesn't mean you did something wrong."),
      bullet("Ask: \"Would I want someone I love to feel this drained?\" You'd want them to set a boundary too."),
      bullet("Start small — practice with low-stakes situations and build up"),
      bullet("Expect pushback — people who benefited from your lack of boundaries will resist the change"),
      heading("When to Get Help"),
      para("If setting boundaries triggers intense anxiety, guilt, or fear — or if you grew up in an environment where your needs were dismissed — therapy can help you build this skill safely."),
      quote("Boundaries aren't punishment for others. They're protection for you."),
    ],
  },
];

// ── Delete orphan drafts + seed ──
console.log("🗑️  Cleaning up draft blog posts...");
const drafts = await client.fetch(`*[_type == "blogPost" && _id in path("drafts.**")]._id`);
if (drafts.length > 0) {
  let tx = client.transaction();
  for (const id of drafts) tx = tx.delete(id);
  await tx.commit();
  console.log(`  Deleted ${drafts.length} drafts`);
}

console.log(`\n📝 Seeding ${posts.length} blog posts with full content...`);

for (const post of posts) {
  await client.createOrReplace({
    _id: `blog-${post.slug}`,
    _type: "blogPost",
    title: post.title,
    slug: { _type: "slug", current: post.slug },
    description: post.description,
    category: post.category,
    publishedAt: post.publishedAt,
    readingTime: post.readingTime,
    published: true,
    body: post.body,
  });
  console.log(`  ✓ ${post.title}`);
}

console.log(`\n✅ Done! ${posts.length} blog posts seeded with full body content.`);
console.log("→ Open Studio: https://mspaultherapies.vercel.app/studio → Blog Posts\n");
